### ISSUE TITLE
Login failed. Waiting for OMP service to become available.

### ISSUE THREAD

**Issue by udiromano** [mikesplain/openvas-docker#108]
Hi,
I'm getting this message when trying to log in after running the openvas 9 docker container.
Do you happen to know what might be the problem?

**Comment by mikesplain** [comment]
The container takes a bit to startup while it scans NVTs etc. As in the Readme, tail the logs and wait for `It seems like your OpenVAS-9 installation is OK`.  After you see that, the web ui should be accessible. To speed up this process, give the container more CPU and memory.

**Comment by mikesplain** [comment]
Please feel free to reopen if you have more issues.
