### ISSUE TITLE
Can't create slave with openvas 9

### ISSUE THREAD

**Issue by udiromano** [mikesplain/openvas-docker#110]
`root@bf4c31c6aca5:/# omp -h localhost -u admin -w admin -i -X - << EOF
> <create_slave>
>    <name>worker-1</name>
>    <comment>worker-1</comment>
>    <host>10.0.0.6</host>
>    <port>9390</port>
>    <login>admin</login>
>    <password>admin</password>
> </create_slave>
> EOF
    <omp_response status_text="Bogus command name" status="400"></omp_response>`

Any idea why?

**Comment by mikesplain** [comment]
What docker command did you use to start up your main server?

**Comment by udiromano** [comment]
I'm using a docker compose file:

`  ovas-manager:
    image: localhost:5000/openvas:latest
    ports:
      - "4000:4000"
      - "9390:9390"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager`

It should be the same as starting it like this:
docker run -d -p 4000:4000 -p 9390:9390 --name openvas mikesplain/openvas:9

Anyway i have openvas 8 installed on another machine (regular installation not docker) and the same command works.

**Comment by mcree** [comment]
I believe the create_slave command has been removed from openvas 9 - it has been replaced with scanners. See: https://wald.intevation.org/scm/viewvc.php?view=revision&root=openvas&revision=26445

**Comment by mcree** [comment]
@udiromano could you please share your composer file?

**Comment by udiromano** [comment]
@mcree I'm sorry i wish i could but i'm not allowed to do so /: If you need help or guidance on specifics feel free to ask...

**Comment by udiromano** [comment]
@mcree Have you managed to create a functional slave scanner?

**Comment by mikesplain** [comment]
This is likely fixed in https://github.com/mikesplain/openvas-docker/pull/109 since `9390` wasn't exposed before.

Please reopen if you see any issues!
