### ISSUE TITLE
Opens 8 - Report results page doesn't show vulnerability name

### ISSUE THREAD

**Issue by udiromano** [mikesplain/openvas-docker#111]
Hey Mike,

I ran a scan with openvas 8.
I look at the scan report in GSA and see vulnerabilities OID instead of name

Here is an example:
http://imgur.com/a/dInT6

Any idea why?

Best regards,

Udi.

**Comment by mikesplain** [comment]
Hi Udi,

Given the issues I've had with OpenVAS 8 and the lack of recent support for
it, I don't know. I would suggest giving 9 a go.
