### ISSUE TITLE
Feature Request - Openvas9 with postgresql

### ISSUE THREAD

**Issue by udiromano** [mikesplain/openvas-docker#112]
I know there was an option to build openvas 8 to work with postgresql instead of mysqlite.
I guess that the same is possible for openvas 9. It will be nice to have openvas9 docker image that support this feature.

**Comment by mikesplain** [comment]
I certainly would be open to this but as I personally don't need the scalability of postgres for OpenVAS, the chances of me getting the time to implement this are slim.  Feel free to open a PR if you figure it out, otherwise I'm marking this a Feature Request for future documentation. Thanks!

**Comment by udiromano** [comment]
I'll work on it soon. I'll release it once it will be complete.

**Comment by falkowich** [comment]
@udiromano Hi, did you have time to work on this? I am thinking of doing the same thing here :)
--
Regards Falk

**Comment by gopherine** [comment]
did it complete ???

**Comment by falkowich** [comment]
@gopherine Hi, Are you asking me, or @udiromano ?

**Comment by gopherine** [comment]
@falkowich i was asking anyone :D who did it so if you did it i would appreciate some help here
