### ISSUE TITLE
Add documentation on how to update the feeds within docker container

### ISSUE THREAD

**Issue by e-alfred** [mikesplain/openvas-docker#126]
Hello,

it would be great to have documentation on how to update the feeds inside the container. In the "Feed Status" page I can only see this:

`Too old (13 days) - Please check the automatic synchronization of your system`

**Comment by mikesplain** [comment]
Hi @e-alfred, we certainly can add some docs here for that. For now, the best option is to pull down a new version of the container (we try to rebuild every few days to give you the latest), or follow the directions on the [OpenVAS site](http://www.openvas.org/openvas-nvt-feed.html).

**Comment by mikesplain** [comment]
You should be able to run that command by exec'ing into the container like this if you're not familiar:
```
docker exec -it <docker container id> bash
greenbone-nvt-sync
```

**Comment by mikesplain** [comment]
Hi @e-alfred did the above help accomplish what you needed? If so I'll add it to the docs but wanted to check back in first! Thanks!

**Comment by carlmolemans** [comment]
for me it does not work. The command is updating, but the update is not available through greenbone. I guess we also need to trigger a database reload ?

**Comment by mikesplain** [comment]
@carlmolemans Ahh yes that makes sense. Can you try running `openvasmd --rebuild --progress` as well after?

**Comment by ybudimirov** [comment]
@mikesplain 

Hi Mike!
```
docker run -d -p 443:443 -v $(pwd)/data:/var/lib/openvas/mgr/ --name openvas mikesplain/openvas
docker exec -it $(docker ps|grep "mikesplain/openvas"|cut -d" " -f1) /bin/bash

root@0980b00ce461:/# greenbone-nvt-sync
...
sent 49,986 bytes  received 6,064,337 bytes  643,612.95 bytes/sec
total size is 266,156,233  speedup is 43.53

root@0980b00ce461:/# openvasmd --rebuild --progress
Rebuilding NVT cache... done.
```

Extras - Feed Status
Changed  from: Too old (15 days)
to: Too old (14 days)

It seems works. Thank you!

**Comment by mikesplain** [comment]
Added! Thanks!
