### ISSUE TITLE
Container fails to rebuild 

### ISSUE THREAD

**Issue by stafot** [mikesplain/openvas-docker#129]
Returns exit code 4 due to invalid url `https://svn.wald.intevation.org/svn/openvas/trunk/tools/openvas-check-setup` 

Tried two alternatives both worked. 
1) `http://svn.wald.intevation.org/svn/openvas/trunk/tools/openvas-check-setup` 
2) `https://raw.githubusercontent.com/jackl0phty/opschef-cookbook-openvas/master/files/default/openvas-check-setup`

**Comment by mikesplain** [comment]
I'm unable to replicate this issue currently. I see that pages cert may have an issue but we had automated build run on docker hub a few hours ago without issue. I'm rerunning tests now.

**Comment by stafot** [comment]
@mikesplain Sorry for this probably was a temporary problem. I retried again the link with `https` and worked. Sorry for any inconvenience caused. My only concern is that in first try i hadn't mark as safe the link on my browser. (which at some point did). So I will try to see if I can replicate it this way.

**Comment by mikesplain** [comment]
@stafot Hey no worries! Thanks for reporting it. The master build I kicked off failed, it doesn't seem related but when I tested that URL a few times I did see some slowness. It may be flakey at the moment but it's still the documented URL for [openvas](http://openvas.org/setup-and-start.html).  Either way just browser testing your URL seems to be faster and more reliable.
