### ISSUE TITLE
User not setup (ERROR: No users found)

### ISSUE THREAD

**Issue by alem0lars-yr** [mikesplain/openvas-docker#136]
When I start the docker container, the user isn't being setup, resulting in error:

```
        ERROR: No users found. You need to create at least one user to log in.
        It is recommended to have at least one user with role Admin.
        FIX: create a user by running 'openvasmd --create-user=<name> --role=Admin && openvasmd --user=<name> --new-password=<password>'
```

I've found that in `start` script the instruction `  echo "Setting up user"` isn't being called so obviously the user is not present.

However, I've checked the `tasks.db` file (post-installation) and it is present.

Who creates `tasks.db`? Is it possible that we need to wait some time or move the check below after services have been started?

**Comment by mikesplain** [comment]
This should be resolved now. Please reopen if you still face this issue!
