### ISSUE TITLE
cannot change web ui port 443

### ISSUE THREAD

**Issue by idan89** [mikesplain/openvas-docker#139]
I am not able to change the port 443 when running the command:

> docker run -d -p 443:443 --name openvas mikesplain/openvas

im already using the port 443 with nginx and Im having conflicts.
the only workaround I found was stopping nginx and re run the command.
would be great to access openvas web using another port instead of 443.

anyone?
thx

**Comment by mikesplain** [comment]
Hi @idan89, you can change the port by changing the first `443` 

```
docker run -d -p 8443:443 --name openvas mikesplain/openvas
```
