### ISSUE TITLE
Openvas scanner does not start

### ISSUE THREAD

**Issue by excal04** [mikesplain/openvas-docker#140]
Hi,

This is on the openvas 8 image, I think it is no longer maintained but it's still on the README. Feel free to close if the project is strictly moving to openvas 9 and kills support for OV8.

I'm getting errors with the `openvas-scanner` not even starting. I followed through the instructions in the README and everything went smooth except that `openvas-check-setup` warned me that OpenVAS Scanner is not running.

Below are the logs I checked so far.

```
root@b8e1777c8a40:/# cat /var/log/openvas/openvassd.messages 
[Thu Oct  5 06:38:44 2017][677] 
/var/lib/openvas/plugins/gb_sphere_ftp_server_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:44 2017][677] /var/lib/openvas/plugins/gb_sphere_ftp_server_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:44 2017][677] 
/var/lib/openvas/plugins/gb_sophos_web_appliance_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:44 2017][677] /var/lib/openvas/plugins/gb_sophos_web_appliance_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:44 2017][677] 
/var/lib/openvas/plugins/gb_sony_ip_cam_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:44 2017][677] /var/lib/openvas/plugins/gb_sony_ip_cam_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:45 2017][677] 
/var/lib/openvas/plugins/gb_speedport_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:45 2017][677] /var/lib/openvas/plugins/gb_speedport_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:45 2017][677] 
/var/lib/openvas/plugins/gb_ssl_cert_chain_get.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:45 2017][677] /var/lib/openvas/plugins/gb_ssl_cert_chain_get.nasl: Could not be loaded
[Thu Oct  5 06:38:45 2017][677] 
/var/lib/openvas/plugins/gb_shibboleth_sp_detect_win.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:45 2017][677] /var/lib/openvas/plugins/gb_shibboleth_sp_detect_win.nasl: Could not be loaded
[Thu Oct  5 06:38:45 2017][677] 
/var/lib/openvas/plugins/gb_south_river_webdrive_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:45 2017][677] /var/lib/openvas/plugins/gb_south_river_webdrive_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:45 2017][677] 
/var/lib/openvas/plugins/gb_snom_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:45 2017][677] /var/lib/openvas/plugins/gb_snom_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:46 2017][677] 
/var/lib/openvas/plugins/gb_schneider_modbus_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:46 2017][677] /var/lib/openvas/plugins/gb_schneider_modbus_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:46 2017][677] 
/var/lib/openvas/plugins/gb_starttls_imap.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:46 2017][677] /var/lib/openvas/plugins/gb_starttls_imap.nasl: Could not be loaded
[Thu Oct  5 06:38:46 2017][677] 
/var/lib/openvas/plugins/gb_starttls_ftp.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:46 2017][677] /var/lib/openvas/plugins/gb_starttls_ftp.nasl: Could not be loaded
[Thu Oct  5 06:38:47 2017][677] 
/var/lib/openvas/plugins/gb_ssl_ciphers_pfs_supported.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:47 2017][677] /var/lib/openvas/plugins/gb_ssl_ciphers_pfs_supported.nasl: Could not be loaded
[Thu Oct  5 06:38:47 2017][677] 
/var/lib/openvas/plugins/gb_splunk_light_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:47 2017][677] /var/lib/openvas/plugins/gb_splunk_light_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:47 2017][677] 
/var/lib/openvas/plugins/gb_sigplus_pro_activex_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:47 2017][677] /var/lib/openvas/plugins/gb_sigplus_pro_activex_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:47 2017][677] 
/var/lib/openvas/plugins/gb_simple_machines_forum_detect.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:47 2017][677] /var/lib/openvas/plugins/gb_simple_machines_forum_detect.nasl: Could not be loaded
[Thu Oct  5 06:38:48 2017][677] 
/var/lib/openvas/plugins/gb_soda_pdf_detect_win.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:48 2017][677] /var/lib/openvas/plugins/gb_soda_pdf_detect_win.nasl: Could not be loaded
[Thu Oct  5 06:38:48 2017][677] 
/var/lib/openvas/plugins/gb_ssl_sni_supported.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:48 2017][677] /var/lib/openvas/plugins/gb_ssl_sni_supported.nasl: Could not be loaded
[Thu Oct  5 06:38:48 2017][677] 
/var/lib/openvas/plugins/gb_starttls_irc.nasl: Parse error at or near line 1

[Thu Oct  5 06:38:48 2017][677] /var/lib/openvas/plugins/gb_starttls_irc.nasl: Could not be loaded
[Thu Oct  5 06:39:32 2017][677] 
/var/lib/openvas/plugins/2009/TinyPHPForum_mult_vuln.nasl: Parse error at or near line 1

[Thu Oct  5 06:39:32 2017][677] /var/lib/openvas/plugins/2009/TinyPHPForum_mult_vuln.nasl: Could not be loaded
[Thu Oct  5 06:39:32 2017][677] 
/var/lib/openvas/plugins/2009/SolarWinds_TFTP.nasl: Parse error at or near line 1

[Thu Oct  5 06:39:32 2017][677] /var/lib/openvas/plugins/2009/SolarWinds_TFTP.nasl: Could not be loaded
[Thu Oct  5 06:39:32 2017][677] Stopped loading plugins: High number of errors.
```

I have not seen those errors elsewhere.

I did re run the commands that sync through the feeds and tried to rebuild. But I guess it won't build when the scanner is down. Anyway, here are logs on the manager.

```
root@b8e1777c8a40:/# cat /var/log/openvas/openvasmd.log      
lib auth:   INFO:2017-03-14 01h37.13 utc:21652: Authentication configuration not found.
md   main:WARNING:2017-03-14 01h37.13 utc:21652: sql_prepare_internal: sqlite3_prepare failed: no such table: main.meta
md   main:WARNING:2017-03-14 01h37.13 utc:21652: sql_x_internal: sql_prepare failed
md   main:WARNING:2017-03-14 01h37.13 utc:21652: database must be initialised from scanner (with --update or --rebuild)
md   main:MESSAGE:2017-03-14 01h37.13 utc:21652: No SCAP database found
md   main:MESSAGE:2017-03-14 01h37.13 utc:21652: No CERT database found
lib auth:   INFO:2017-03-14 01h37.20 utc:21653: Authentication configuration not found.
md   main:WARNING:2017-03-14 01h37.20 utc:21653: database must be initialised from scanner (with --update or --rebuild)
md   main:MESSAGE:2017-03-14 01h37.20 utc:21653: No SCAP database found
md   main:MESSAGE:2017-03-14 01h37.20 utc:21653: No CERT database found
lib auth:   INFO:2017-03-14 01h37.20 utc:21654: Authentication configuration not found.
md   main:WARNING:2017-03-14 01h37.20 utc:21654: database must be initialised from scanner (with --update or --rebuild)
md   main:MESSAGE:2017-03-14 01h37.20 utc:21654: No SCAP database found
md   main:MESSAGE:2017-03-14 01h37.20 utc:21654: No CERT database found
md   main:WARNING:2017-10-05 06h38.40 utc:666: database must be initialised from scanner (with --update or --rebuild)
lib auth:   INFO:2017-10-05 06h38.40 utc:666: Authentication configuration not found.
md    otp:MESSAGE:2017-10-05 06h38.41 utc:680: Scanner loading: No information provided. SCANNER_LOADING <|> 0 <|> 0

md    otp:MESSAGE:2017-10-05 06h38.52 utc:681: Scanner loading: 650 / 55675 nvts.
md    otp:MESSAGE:2017-10-05 06h39.03 utc:682: Scanner loading: 2150 / 55675 nvts.
md    otp:MESSAGE:2017-10-05 06h39.14 utc:683: Scanner loading: 4500 / 55675 nvts.
md    otp:MESSAGE:2017-10-05 06h39.26 utc:684: Scanner loading: 6300 / 55675 nvts.
lib  serv:WARNING:2017-10-05 06h39.36 utc:685: openvas_server_connect: failed to connect to server: Connection refused
```

I ran the image like so:
`docker run -p 443:443 -p 9390:9390 --name openvas mikesplain/openvas:8`

Thanks in advance!

**Comment by mikesplain** [comment]
Hi @ excal04, thanks for checking in. We haven't maintained openvas 8 since 9 has been much more stable.  We'll update the docs!

Thanks

**Comment by bappa92chakraborty** [comment]
Hey Hi, I am using openvas 9, but here also my scanner is not working can you please help me out.

Step 5: Checking OpenVAS CLI ... 
        OK: OpenVAS CLI version 1.4.5.
Step 6: Checking Greenbone Security Desktop (GSD) ... 
        SKIP: Skipping check for Greenbone Security Desktop.
Step 7: Checking if OpenVAS services are up and running ... 
        OK: netstat found, extended checks of the OpenVAS services enabled.
        ERROR: OpenVAS Scanner is NOT running!
        FIX: Start OpenVAS Scanner (openvassd).
        WARNING: OpenVAS Manager is running and listening only on the local interface.
        This means that you will not be able to access the OpenVAS Manager from the
        outside using GSD or OpenVAS CLI.
        SUGGEST: Ensure that OpenVAS Manager listens on all interfaces unless you want
        a local service only.
        WARNING: Greenbone Security Assistant is running and listening only on the local interface.
        This means that you will not be able to access the Greenbone Security Assistant from the
        outside using a web browser.
        SUGGEST: Ensure that Greenbone Security Assistant listens on all interfaces.
        OK: Greenbone Security Assistant is listening on port 9392, which is the default port.

 ERROR: Your OpenVAS-9 installation is not yet complete!

Please follow the instructions marked with FIX above and run this
script again.

If you think this result is wrong, please report your observation
and help us to improve this check routine:
http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss
Please attach the log-file (/tmp/openvas-check-setup.log) to help us analyze the problem.

**Comment by bk5839** [comment]
@bappa92chakraborty

Simply follow my steps it works for me

firstly go to 

/var/cache and move the openvas directory to openvas-bak

now remove the openvas with the help of 

yum remove -y openvas
and again install the openvas
yum install -y openvas
openvas-setup

now the openvas will works fine and good

reply in case u face any more problem

**Comment by bappa92chakraborty** [comment]
Hey Hi,

Thank you so much for replying me back but I have faced this issue in Kali
Linux and I think this command is for Unix based OS, an even openvas-bak
folder is not there. I uninstall openvas and again install openvas, Here is
the error which I get according to command:

#openvas-setup


● openvas-scanner.service - Open Vulnerability Assessment System Scanner
Daemon
   Loaded: loaded (/lib/systemd/system/openvas-scanner.service; disabled;
vendor preset: disabled)
   Active: failed (Result: timeout) since Mon 2018-08-06 11:06:01 IST; 25s
ago
     Docs: man:openvassd(8)
           http://www.openvas.org/
  Process: 8098 ExecStart=/usr/sbin/openvassd
--unix-socket=/var/run/openvassd.sock (code=killed, signal=TERM)

Aug 06 11:04:30 kali systemd[1]: Starting Open Vulnerability Assessment
System Scanner Daemon...
Aug 06 11:06:01 kali systemd[1]: openvas-scanner.service: Start operation
timed out. Terminating.
Aug 06 11:06:01 kali systemd[1]: openvas-scanner.service: Failed with
result 'timeout'.
Aug 06 11:06:01 kali systemd[1]: Failed to start Open Vulnerability
Assessment System Scanner Daemon.

● openvas-manager.service - Open Vulnerability Assessment System Manager
Daemon
   Loaded: loaded (/lib/systemd/system/openvas-manager.service; disabled;
vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:openvasmd(8)
           http://www.openvas.org/

Aug 06 10:45:21 kali systemd[1]: Starting Open Vulnerability Assessment
System Manager Daemon...
Aug 06 10:45:21 kali systemd[1]: openvas-manager.service: Can't open PID
file /var/run/openvasmd.pid (yet?) after start: No such file or directory
Aug 06 10:45:22 kali systemd[1]: Started Open Vulnerability Assessment
System Manager Daemon.
Aug 06 10:51:46 kali systemd[1]: Stopping Open Vulnerability Assessment
System Manager Daemon...
Aug 06 10:51:47 kali systemd[1]: Stopped Open Vulnerability Assessment
System Manager Daemon.

[>] Starting openvassd


-openvassd is not at all running. it gets stuck over here



#openvas-check-setup



Step 2: Checking OpenVAS Manager ...
        OK: OpenVAS Manager is present in version 7.0.3.
        OK: OpenVAS Manager database found in /var/lib/openvas/mgr/tasks.db.
        OK: Access rights for the OpenVAS Manager database are correct.
        OK: sqlite3 found, extended checks of the OpenVAS Manager
installation enabled.
        OK: OpenVAS Manager database is at revision 184.
        OK: OpenVAS Manager expects database at revision 184.
        OK: Database schema is up to date.
        OK: OpenVAS Manager database contains information about 46503 NVTs.
        OK: At least one user exists.
        OK: OpenVAS SCAP database found in
/var/lib/openvas/scap-data/scap.db.
        OK: OpenVAS CERT database found in
/var/lib/openvas/cert-data/cert.db.
        OK: xsltproc found.
Step 3: Checking user configuration ...
        WARNING: Your password policy is empty.
        SUGGEST: Edit the /etc/openvas/pwpolicy.conf file to set a password
policy.
Step 4: Checking Greenbone Security Assistant (GSA) ...
        OK: Greenbone Security Assistant is present in version 7.0.3.
        OK: Your OpenVAS certificate infrastructure passed validation.
Step 5: Checking OpenVAS CLI ...
        OK: OpenVAS CLI version 1.4.5.
Step 6: Checking Greenbone Security Desktop (GSD) ...
        SKIP: Skipping check for Greenbone Security Desktop.
Step 7: Checking if OpenVAS services are up and running ...
        OK: netstat found, extended checks of the OpenVAS services enabled.
        ERROR: OpenVAS Scanner is NOT running!
        FIX: Start OpenVAS Scanner (openvassd).
        ERROR: OpenVAS Manager is NOT running!
        FIX: Start OpenVAS Manager (openvasmd).
        ERROR: Greenbone Security Assistant is NOT running!
        FIX: Start Greenbone Security Assistant (gsad).

 ERROR: Your OpenVAS-9 installation is not yet complete!

Please follow the instructions marked with FIX above and run this
script again.

If you think this result is wrong, please report your observation
and help us to improve this check routine:
http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss
Please attach the log-file (/tmp/openvas-check-setup.log) to help us
analyze the problem.


-This is the error for openvas-check-setup

**Comment by Yogi-1999** [comment]
openvas-scanner.service - Open Vulnerability Assessment System Scanner Daemon
   Loaded: loaded (/lib/systemd/system/openvas-scanner.service; disabled; vendor preset: disabled)
   Active: failed (Result: signal) since Sun 2019-07-14 20:08:52 IST; 124ms ago
     Docs: man:openvassd(8)
           http://www.openvas.org/
please solve this problem

**Comment by SaraJ52** [comment]
@bk5839  I was trying the solution you have told and I am having an error that says no such directory as "openvas" exists

**Comment by SaraJ52** [comment]
@bk5839 

![image](https://user-images.githubusercontent.com/59283205/115427347-404f7100-a1b6-11eb-9c6b-5b60cba7cd24.png)
