### ISSUE TITLE
Cannot install this docker

### ISSUE THREAD

**Issue by ccsliinc** [mikesplain/openvas-docker#144]
Any idea what could be wrong?

[~] # docker pull mikesplain/openvas
Using default tag: latest
latest: Pulling from mikesplain/openvas
660c48dd555d: Pull complete 
4c7380416e78: Pull complete 
421e436b5f80: Pull complete 
e4ce6c3651b3: Pull complete 
be588e74bd34: Pull complete 
39ba35499809: Pull complete 
eb6c913ec15f: Pull complete 
4f416fdac70d: Pull complete 
2c95ef8672b3: Pull complete 
a788e9bbe800: Extracting [==================================================>] 262.8 MB/262.8 MB
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: open /var/lib/openvas/plugins/2010/gb_fedora_2010_14678_samba_fc12.nasl.asc: no space left on device

**Comment by mikesplain** [comment]
I believe this means you don’t have enough free disk space for this docker container. Free up some disk space and try again.

**Comment by ccsliinc** [comment]
I checked, there are tb free, and over 90% inodes free.  Just wondering if you ever saw that before.

**Comment by mikesplain** [comment]
I have not seen this issue.  Can you provide the output of `docker info`

**Comment by ccsliinc** [comment]
[~] # docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.11.2
Storage Driver: devicemapper
 Pool Name: docker-252:0-171018248-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 2.18 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105.2 GB
 Metadata Space Used: 4.784 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /share/CACHEDEV1_DATA/Containers/container-station-data/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /share/CACHEDEV1_DATA/Containers/container-station-data/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.2.8
Operating System: QTS 4.3.3 (20171117)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.672 GiB
Name: QNAP
ID: BYID:WSEQ:I4SO:OH4P:YHOD:HK5V:NWTA:FPMG:XCFB:RK5I:PHAS:KELX
Docker Root Dir: /share/CACHEDEV1_DATA/Containers/container-station-data/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Labels:
 architecture=x86_64

**Comment by mikesplain** [comment]
@ccsliinc are you still seeing this issue? Please reopen if you are.
