### ISSUE TITLE
UI not available 

### ISSUE THREAD

**Issue by SyCode7** [mikesplain/openvas-docker#145]
I have just pulled this image and started the container. According to the instructions,  http://<machine-name> should peovide the interface for the web ui, howeverr this is not the case. I also tried other combinations e.g. http://localhost, http://localhost:4000 ... there is no joy yet !! What could be wrong 

I have the following messages in the log (openvasmd.messages)

`[Mon Mar  6 20:54:33 2017][1359] Client closed the communication
[Mon Mar  6 20:54:49 2017][837] Received the Terminated signal
[Fri Dec  1 13:01:07 2017][24] openvassd 5.1.0 started
[Fri Dec  1 13:01:49 2017][117] Client closed the communication
[Fri Dec  1 13:13:42 2017][24] Reloading the scanner.
[Fri Dec  1 13:18:20 2017][24] Finished reloading the scanner.
[Fri Dec  1 13:19:08 2017][633] Client closed the communication
[Fri Dec  1 13:19:21 2017][654] Client closed the communication
`

**Comment by mikesplain** [comment]
Hi @SyCode7, in our docker command we mount the container to port 443 ( `-p 443:443`).  The ui should be accessible at https://localhost.  If 443 isn't available for you to mount to, you can do something like:

```
docker run -d -p 8443:443 --name openvas mikesplain/openvas
```
which will make your portal accessible at `https://localhost:8443`.

Please re-open if you have additional issues.
