### ISSUE TITLE
Failed to create credentials

### ISSUE THREAD

**Issue by chetanagrawal** [mikesplain/openvas-docker#150]
Hi, I tried lauching openvas9 docker container on Ubuntu 14.04 and CentOS7 and in both the cases I am facing issues while creating credentials. I get the following error:

 "An internal error occurred while creating a new credential. It is unclear whether the credential has been created or not. Diagnostics: Failure to receive response from manager daemon."

I checked the /var/log/openvas/openvasmd.log and found below error:
GLib:UNKNOWN:2018-01-11 06h38.29 UTC:401: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:100: failed to allocate 18446744073624896127 bytes

Can someone suggest how to fix this?

**Comment by biohazd** [comment]
i also have it failing to create credentials <create_credentials>, but mine just hangs there and never bring the command prompt back.   <get_credentials> works fine.

**Comment by tnt335** [comment]
Same issue here, Openvas v9.  the error only occurs when I try to create cred with SSH.  Creating creds with username/password works fine
