### ISSUE TITLE
Docker Image Is broken.

### ISSUE THREAD

**Issue by jcostello84** [mikesplain/openvas-docker#152]
Hello @mikesplain!

First, thanks for such an awesome project. I really like it a lot! I wanted to give you a heads up that I pulled the latest mikesplain/openvas image from docker hub and it's broken. I cloned your repo locally and rebuilt the image, and everything works as expected, so I think that there might be a error which is failing silently in your build process. I have attached my logs from the mikesplain/openvas container which is failing.

[openvas.txt](https://github.com/mikesplain/openvas-docker/files/1644217/openvas.txt)

Here is where I think the build is failing silently on redis:

[silent_failure.txt](https://github.com/mikesplain/openvas-docker/files/1644229/silent_failure.txt)

I think you just need to rebuild and push the container, and things should be fine. Thanks again!

Cheers!

**Comment by mikesplain** [comment]
@jcostello84 Odd, it's all automated so I'll kick docker hub to rebuild. Thanks for the report!

**Comment by jcostello84** [comment]
@mikesplain Awesome! Thanks for the quick response. If you message me when it's done, I'll gladly test it out for you right away.

**Comment by mikesplain** [comment]
@jcostello84 Awesome thanks! It's building now, I'll let you know.

https://hub.docker.com/r/mikesplain/openvas/builds/b2cqxgrwzw2ndztlnj2ewqd/

**Comment by jcostello84** [comment]
@mikesplain That fixed it! Thanks.
