### ISSUE TITLE
Not Generating Reports

### ISSUE THREAD

**Issue by arnydo** [mikesplain/openvas-docker#154]
Hi! I recently deployed two OpenVas containers to two separate machines and both don't seem to be generating reports.

I was able to run Wireshark and verify that the scanning was occuring and comms were going on but once complete there was nothing in the report.

I also replicated this on an old(er) instance of OpenVas and it did the same thing.

Any ideas of what I can check to see what is going on?

**Comment by mikesplain** [comment]
The component that generates reports in PDF would be `latex`.  Do you have more details of what you're running into? Maybe a log would be helpful.  Thanks!
