### ISSUE TITLE
Docker container cant update/sync

### ISSUE THREAD

**Issue by Noname2244** [mikesplain/openvas-docker#155]
root@f990e6f42267:/# greenbone-nvt-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

from the host running docker

ping feed.openvas.org
PING dl.greenbone.net (89.146.224.58) 56(84) bytes of data.
64 bytes from dl.greenbone.net (89.146.224.58): icmp_seq=1 ttl=51 time=40.1 ms
64 bytes from dl.greenbone.net (89.146.224.58): icmp_seq=2 ttl=51 time=39.9 ms

**Comment by mikesplain** [comment]
This should be resolved now. Please reopen if you still face this issue!
