### ISSUE TITLE
Update README.md with NVT + CERT + SCAP database feeds

### ISSUE THREAD

**Issue by naman** [mikesplain/openvas-docker#160]
According to t[his blog](https://sysadmin-ramblings.blogspot.in/2017/04/update-openvas-feeds.html), (have confirmed, it works) I think it would be safe to add the following code snippet for those who want to update all the three databases 

```
    greenbone-nvt-sync
    greenbone-certdata-sync
    greenbone-scapdata-sync
    openvasmd --update --verbose --progress

    /etc/init.d/openvas-manager restart
    /etc/init.d/openvas-scanner restart
```

**Comment by mikesplain** [comment]
@naman This should now be fixed via https://github.com/mikesplain/openvas-docker/pull/170

Thanks for the tips!
