### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by Noname2244** [mikesplain/openvas-docker#162]
root@9d347a932612:/# greenbone-nvt-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

also ping isnt availble in the container.

**Comment by mikesplain** [comment]
Are you still facing this issue? You can install ping in the container by execing into it and `apt update && apt install iputils-ping` as normal.

**Comment by Noname2244** [comment]
:root /$ ping 89.146.224.58
PING 89.146.224.58 (89.146.224.58) 56(84) bytes of data.
64 bytes from 89.146.224.58: icmp_seq=1 ttl=50 time=38.7 ms
64 bytes from 89.146.224.58: icmp_seq=2 ttl=50 time=38.1 ms
64 bytes from 89.146.224.58: icmp_seq=3 ttl=50 time=38.3 ms
^C
--- 89.146.224.58 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 38.196/38.453/38.784/0.333 ms

**Comment by Noname2244** [comment]
Ip connectivity is fine, still cant update tho

root@9d347a932612:/# greenbone-nvt-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
root@9d347a932612:/# greenbone-nvt-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
root@9d347a932612:/# greenbone-nvt-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
root@9d347a932612:/# greenbone-certdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]
root@9d347a932612:/# greenbone-scapdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

**Comment by silentbreaksec** [comment]
Try it with curl instead of wget...that worked for me. 

`greenbone-nvt-sync --curl --verbose`

**Comment by Noname2244** [comment]
That solved the NVT update , thanx!

**Comment by Noname2244** [comment]
Any other workaround for the other syncs?
greenbone-certdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Cannot assign requested address (99)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

**Comment by pchamo** [comment]
This issue is still present. Only greenbone-nvt-sync works. The other two scripts fail:

[root@ovmgr]# greenbone-certdata-sync --curl --verbose
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1648) [Receiver=3.1.2]

[root@ovmgr]# greenbone-scapdata-sync --curl --verbose
rsync: did not see server greeting
rsync error: error starting client-server protocol (code 5) at main.c(1648) [Receiver=3.1.2]

Is there any workaround?

Thank you.

**Comment by jmcarranza** [comment]
I'm behind a corporate proxy and I had to open TCP port 873 on our firewall, then set the environment variable RSYNC_PROXY=my-proxy:8080

**Comment by pchamo** [comment]
It's not a firewall issue. It seems that only the NVT feed is available in the openvas demo version! Thank you.

**Comment by jmcarranza** [comment]
I use the open source version and I can update all the feeds that way.

**Comment by pchamo** [comment]
Look at this please:
[root@ovmgr ~]# telnet feed.openvas.org 873
Trying 89.146.224.58...
Connected to feed.openvas.org.
Escape character is '^]'.
Connection closed by foreign host.

But, doing a telnet to other server that has the rsync port open, the result is:

[user@server ~]$ telnet server1 873
Trying 172.xx.x.xxx...
Connected to server.xxx.xxx.xx (172.xx.x.xxx).
Escape character is '^]'.
@RSYNCD: 31.0

Could you try a telnet to feed.openvas.org 873 and share the result please?

**Comment by lundbergaj** [comment]
I had this problem with a recent install, and running the nvt update would work using --wget, but the scap or cert updates wouldn't work with anything I could find. Looking around, I found this discussion:
http://lists.wald.intevation.org/pipermail/openvas-discuss/2018-September/012190.html
The writer notes that at least for some machines, the update script connected to the server twice, causing it to be blocked. Adding a sleep 5 after the FEED_SERVER_SERVER test in all three scripts made them all work for me. If you're having trouble with the scripts getting rejected, try adding a sleep 5 to them.

**Comment by Syphontwo** [comment]
> Adding a sleep 5 after the FEED_SERVER_SERVER test in all three scripts made them all work for me. If you're having trouble with the scripts getting rejected, try adding a sleep 5 to them.

I added a sleep 5 to `greenbone-scapdata-sync` and `greenbone-certdata-sync` immediately after the line 
```
FEED_VERSION_SERVER=`cat $FEED_INFO_TEMP_DIR/timestamp`
```
unfortunately this had no effect.
```
/usr/sbin/greenbone-scapdata-sync --curl --verbose
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
```

As others reported, the NVT database connection works no problem.  One person mentioned that these databases are not available in the open source version, but another said it was.  Do we have any official word or documentation on the availability?

> I'm behind a corporate proxy and I had to open TCP port 873 on our firewall, then set the environment variable RSYNC_PROXY=my-proxy:8080

This is my next step, but i won't be able to get to it for a while.  I may try another location without the firewall and see if that's the issue.

**Comment by isweluiz** [comment]
I have the same problem

**Comment by bannsec** [comment]
Bumping this to keep it open as it is still an issue.

**Comment by bannsec** [comment]
Bumping as this is still an issue over a year later.

**Comment by stewiem2000** [comment]
I found through tcpdump'ing that, for example, greenbone-certdata-sync executes rsync more than once and, on our system/network at least, the next rsync-call's SYN gets received before the first's FIN/ACK comes back — thus the server probably thinks there are multiple connections from the same IP (which is blocked).  Simply adding a "sleep 1;" after (the error checking) of each/all rsync commands resolved this issue for me.

**Comment by pakoota** [comment]
> Try it with curl instead of wget...that worked for me.
> 
> `greenbone-nvt-sync --curl --verbose`

Great.
Thanks.
Solved.

**Comment by acosonic** [comment]
Same problem now...

**Comment by acosonic** [comment]
> Same problem now...

Still no changes, tried curl, tried everything...

**Comment by Power-G** [comment]
Me too...

**Comment by dimazarno** [comment]
same here

**Comment by MarksenDE** [comment]
Any update about this issue? I have the same problem ...

**Comment by Sunnyvij** [comment]
It is not working with Curl or wget or just direct install greenbone .....
Try the other link : greenbone-nvt-sync --rsync  stil does not work  all they are saying on there support channel is to use rsync... Whats is the problem here ..

**Comment by rforberger** [comment]
I think they changed the rsync mirror from feed.openvas.org to feed.community.greenbone.net. Not 100% sure though. 
I just downloaded the most recent container image from hub.docker.com, but it looks like it's still using feed.openvas.org....

**Comment by mkopec3** [comment]
> I think they changed the rsync mirror from feed.openvas.org to feed.community.greenbone.net. Not 100% sure though.
> I just downloaded the most recent container image from hub.docker.com, but it looks like it's still using feed.openvas.org....

It seems so. Solved it by:
`root@3b8d28ae4ccf:/# echo "45.135.106.142 feed.community.greenbone.net feed.openvas.org" >> /etc/hosts`

**Comment by jfortier** [comment]
@mkopec3 thanks so much, just realized my scanner has not been updating, when I went to find out why, just getting timeouts. I suppose if I upgrade the build this likely won't be an issue.

**Comment by zitstif** [comment]
@mkopec3  Thanks for that one liner!

**Comment by infra-ray** [comment]
> > I think they changed the rsync mirror from feed.openvas.org to feed.community.greenbone.net. Not 100% sure though.
> > I just downloaded the most recent container image from hub.docker.com, but it looks like it's still using feed.openvas.org....
> 
> It seems so. Solved it by:
> `root@3b8d28ae4ccf:/# echo "45.135.106.142 feed.community.greenbone.net feed.openvas.org" >> /etc/hosts`

Thanks. It really helps me.

**Comment by sailslack** [comment]
> > > I think they changed the rsync mirror from feed.openvas.org to feed.community.greenbone.net. Not 100% sure though.
> > > I just downloaded the most recent container image from hub.docker.com, but it looks like it's still using feed.openvas.org....
> > 
> > 
> > It seems so. Solved it by:
> > `root@3b8d28ae4ccf:/# echo "45.135.106.142 feed.community.greenbone.net feed.openvas.org" >> /etc/hosts`
> 
> Thanks. It really helps me.

It worked for me too. Many thanks.

**Comment by 740355215** [comment]
> > I think they changed the rsync mirror from feed.openvas.org to feed.community.greenbone.net. Not 100% sure though.
> > I just downloaded the most recent container image from hub.docker.com, but it looks like it's still using feed.openvas.org....
> 
> It seems so. Solved it by:
> `root@3b8d28ae4ccf:/# echo "45.135.106.142 feed.community.greenbone.net feed.openvas.org" >> /etc/hosts`

Works well. Thank you !

**Comment by makarov20211221** [comment]
root@232289daebe0:/# echo "45.135.106.142 feed.community.greenbone.net feed.openvas.org" >> /etc/hosts
root@232289daebe0:/# greenbone-nvt-sync
rsync: failed to connect to feed.openvas.org (45.135.106.142): Connection refused (111)
rsync: failed to connect to feed.openvas.org (45.135.106.142): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(128) [Receiver=3.1.1]

**Comment by ImPerec777** [comment]
Try to change ip to 45.135.106.143 :
`echo "45.135.106.143 feed.community.greenbone.net feed.openvas.org" >> /etc/hosts`
