### ISSUE TITLE
openvasmd constantly not available

### ISSUE THREAD

**Issue by cvernooy23** [mikesplain/openvas-docker#163]
After running the docker container, waiting for the updates, creating a user and then trying to login I just get "Login failed. Waiting for OMP service to become available."

root@8ac11cd3ad05:/# service --status-all | grep openvas
```
...
 [ + ]  openvas-gsa
 [ + ]  openvas-manager
 [ + ]  openvas-scanner
```

all services started using ./startup in the docker shell and openvas-check-setup passed with no errors

```
...
It seems like your OpenVAS-9 installation is OK.
...
```

**Comment by mikesplain** [comment]
That's odd. How much memory and CPU is available for the container?
