### ISSUE TITLE
Newbie looking for guidance

### ISSUE THREAD

**Issue by patruff** [mikesplain/openvas-docker#164]
Hi, I'm new to Docker and to OpenVAS so please keep that in mind. I have VirtualBox for Windows (8) installed and am using Docker through that. I'm able to get the image and things seem fine until I try to access the Web UI. I've looked into the machine's IP and it tries to connect but nothing (I don't think it's my firewall, but maybe that's the issue). I checked the logs (inside Bash on the Docker machine) and I see this. Any ideas?

![image](https://user-images.githubusercontent.com/14841709/37981308-594948e8-31bb-11e8-93ca-f96f42a86850.png)

**Comment by patruff** [comment]
Nevermind, I needed to dedicate more memory to the process

**Comment by mikesplain** [comment]
@patruff Sorry for the delay, are you sure you're using https:// ? openvas creates it's own cert by default so you'll have to make sure you're on https.
