### ISSUE TITLE
Dirb, arachni, nikto are not available in this docker image

### ISSUE THREAD

**Issue by tshrinivasan** [mikesplain/openvas-docker#17]
Dirb, arachni, nikto are not available in this docker image.

getting error messages like

Vulnerability Detection Result
Nikto could not be found in your system path.
OpenVAS was unable to execute Nikto and to perform the scan you
requested.
Please make sure that Nikto is installed and that nikto.pl or nikto is
available in the PATH variable defined for your environment.

Please add these to the image.

Thanks for the great works.

**Comment by mikesplain** [comment]
Hi, can you explain to to replicate that error? I'll make sure to add them. Thanks!

**Comment by mikesplain** [comment]
These have been added but I discovered an issue with Docker hub building these images. Fixing in #22 hopefully.
