### ISSUE TITLE
admin http interface cant be accessed after deplyment

### ISSUE THREAD

**Issue by Ondjultomte** [mikesplain/openvas-docker#177]
There is only this error message in the browser

`The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it.`

Entering `gsad --allow-header-host "internal IP hos the host" ` in the openvas console doesnt help.
Got that tip from:
https://lists.wald.intevation.org/pipermail/openvas-discuss/2018-April/011929.html

**Comment by Noname2244** [comment]
I have older installations that was updated and have the same problem now.

This docker is currently none functional.

**Comment by lanarchy** [comment]
Same issue here, new, fresh install

**Comment by brianclemens** [comment]
I had the same issue.  I fixed it by adding the ALLOW_HEADER_HOST environmental variable to my docker-compose.
```yaml
services:
  openvas:
    environment:
      - ALLOW_HEADER_HOST="vas.mydomain.com"
```
@Ondjultomte you were looking at the right thing, but you'd either want to set it as an environmental variable or edit /etc/default/openvas-gsad and restart the gsad service with `/etc/init.d/openvas-gsa restart`

**Comment by lanarchy** [comment]
I was able to uncomment the ALLOW_HEADER_HOST and add in the IP I am serving it from and that worked.

**Comment by boomshadow** [comment]
This is a duplicate of #168  A fix was already merged in.
You have to run the container while specifying the public-facing IP or hostname. This is in the project README:

    docker run -d -p 443:443 -e PUBLIC_HOSTNAME=myopenvas.example.org --name openvas mikesplain/openvas

**Comment by Noname2244** [comment]
I can login now but cant access the backend

![image](https://user-images.githubusercontent.com/34089487/39910855-6a303fa2-54f9-11e8-84cd-adf724106cdf.png)

**Comment by sicarii-13** [comment]
Tried Boomshadows fix keep having this issue. 

![image](https://user-images.githubusercontent.com/9999905/43456001-17c9a6c8-94c2-11e8-9dbd-617cd1d3c86b.png)
No clue why.

**Comment by SyCode7** [comment]
I still have this issue,is there a work around ? This is the error I see in the browser :  `The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it.`
