### ISSUE TITLE
greenbone sync problem

### ISSUE THREAD

**Issue by answerz0r** [mikesplain/openvas-docker#185]
Please help me with greenbone-scapdata-sync and greenbone-certdata-sync i have reponse: Network is unreachable (101) and connection timed out (101) every time im trying to do that. 
Im trying to do that because i have an error when trying to launch openvas on browser (SCAP and/or CERT database missing on OMP server). 

only command greenbone-nvt-sync worked but with --curl --verbose (nothing more cant work). 

Help pls

**Comment by fabionitto** [comment]
Have you checked your firewall?

**Comment by answerz0r** [comment]
I have no firewall and i tried using internet from my cellphone hotspot and normal wifi or cable. 
Errors: 

root@kali:~# greenbone-scapdata-sync 
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
root@kali:~# greenbone-nvt-sync 
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
root@kali:~# openvas-feed-update 
[>] Updating OpenVAS feeds
[*] [1/3] Updating: NVT
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
[*] [2/3] Updating: Scap Data
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
[*] [3/3] Updating: Cert Data
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
root@kali:~# greenbone-
greenbone-certdata-sync  greenbone-nvt-sync       greenbone-scapdata-sync
root@kali:~# greenbone-certdata-sync 
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]


also check setup show me that info: 

root@kali:~# openvas-check-setup 
openvas-check-setup 2.3.7
  Test completeness and readiness of OpenVAS-9

  Please report us any non-detected problems and
  help us to improve this check routine:
  http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss

  Send us the log-file (/tmp/openvas-check-setup.log) to help analyze the problem.

  Use the parameter --server to skip checks for client tools
  like GSD and OpenVAS-CLI.

Step 1: Checking OpenVAS Scanner ... 
        OK: OpenVAS Scanner is present in version 5.1.1.
        OK: redis-server is present in version v=4.0.10.
        OK: scanner (kb_location setting) is configured properly using the redis-server socket: /var/run/redis-openvas/redis-server.sock
        OK: redis-server is running and listening on socket: /var/run/redis-openvas/redis-server.sock.
        OK: redis-server configuration is OK and redis-server is running.
        OK: NVT collection in /var/lib/openvas/plugins contains 46013 NVTs.
        WARNING: Signature checking of NVTs is not enabled in OpenVAS Scanner.
        SUGGEST: Enable signature checking (see http://www.openvas.org/trusted-nvts.html).
        OK: The NVT cache in /var/cache/openvas contains 46013 files for 46013 NVTs.
Step 2: Checking OpenVAS Manager ... 
        OK: OpenVAS Manager is present in version 7.0.2.
        OK: OpenVAS Manager database found in /var/lib/openvas/mgr/tasks.db.
        OK: Access rights for the OpenVAS Manager database are correct.
        OK: sqlite3 found, extended checks of the OpenVAS Manager installation enabled.
        OK: OpenVAS Manager database is at revision 184.
        OK: OpenVAS Manager expects database at revision 184.
        OK: Database schema is up to date.
        OK: OpenVAS Manager database contains information about 46009 NVTs.
        OK: At least one user exists.
        ERROR: No OpenVAS SCAP database found. (Tried: /var/lib/openvas/scap-data/scap.db)
        FIX: Run a SCAP synchronization script like greenbone-scapdata-sync.

 ERROR: Your OpenVAS-9 installation is not yet complete!

Please follow the instructions marked with FIX above and run this
script again.

If you think this result is wrong, please report your observation
and help us to improve this check routine:
http://lists.wald.intevation.org/mailman/listinfo/openvas-discuss
Please attach the log-file (/tmp/openvas-check-setup.log) to help us analyze the problem.


Ofcourse thats dont work as you can see above

**Comment by mikesplain** [comment]
I just tested and connectivity is working fine. This generally happens when there's an issue like a firewall (as @fabionitto mentioned above). I don't think this is our docker container's issue at the moment :(

**Comment by answerz0r** [comment]
Tu ani you for answers. I will try what i can do nad i will lat you know what happens ;)

**Comment by ethhack** [comment]
Currently receiving the following, and have been since last evening:

[root@scanner:~# greenbone-certdata-sync
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection refused (111)
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)

**Comment by riccardo-brazzale** [comment]
Hello, 
I've a new installation on debian, syncing certdata and scapdata give me these errors:
rsync: failed to connect to feed.openvas.org (89.146.224.58): Connection timed out (110)s:
rsync: failed to connect to feed.openvas.org (2a01:130:2000:127::d1): Network is unreachable (101)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

**Comment by calve** [comment]
fwiw you can run both those scripts with `--refresh` arguments to avoid modifying it by hand

**Comment by daniejstriata** [comment]
What port is needed to be open for the rsync? 873?

**Comment by ilovesusu** [comment]
> 您好，
> 我在debian上进行了新安装，同步certdata和scapdata给我这些错误：
> rsync：无法连接到feed.openvas.org（89.146.224.58）：连接超时（110）s：
> rsync：连接失败to feed.openvas.org（2a01：130：2000：127 :: d1）：网络无法访问（101）
> rsync错误：clientserver.c上的套接字IO（代码10）中的错误（125）[Receiver = 3.1.2]

$cat /usr/bin/openvas-feed-update 
#!/bin/bash
echo "Updating OpenVas Feeds"
greenbone-nvt-sync
greenbone-scapdata-sync
greenbone-certdata-sync --wget


it work

**Comment by kevinchugh** [comment]
`greenbone-scapdata-sync --wget` worked for me FWIW after getting the rsync connection refused error

**Comment by leandro92correia** [comment]
This problem is cause by NAT when you're using a virtual machine. This problem can be fixed by changing the network connection to "BRIDGE MODE".

**Comment by hughesjs** [comment]
I'm having the same problem, it seems to work after I run the command a number of times, I've checked my firewall and IIDS and neither of those are interfering. Any ideas?
