### ISSUE TITLE
Openvas Scanner 5.1.2 Hangs for Several Hours on Scans

### ISSUE THREAD

**Issue by egerod** [mikesplain/openvas-docker#209]
The docker image currently use Openvas Scanner 5.1.2, with contains a bug that causes scans to hang at 1% completion for several hours while consuming 100% CPU.

This bug have been fixed in 5.1.3, so updating to the new release should fix the issue.

Details:
- https://community.greenbone.net/t/community-feed-unusable/132

- https://github.com/greenbone/openvas-scanner/releases/tag/v5.1.3

**Comment by boarnoah** [comment]
This explains whats going on, I spent a few hours thinking it was my local network.

I notice in the linked thread they mention that OpenVas on Kali's repositories is updated with the fix. Haven't had any luck getting it to work there myself. Did you by any chance check it out too @egerod ?

**Comment by egerod** [comment]
@boarnoah no, haven't looked at fixing the current image, as I build an extra layer on the image, I was able to revert to an old image.

**Comment by rowanruseler** [comment]
This is easily resolved:
```
docker exec it openvas bash
apt update
apt upgrade
apt-cache policy openvas9-scanner
```

should result in:
```
openvas9-scanner:
  Installed: 5.1.3-1
  Candidate: 5.1.3-1
  Version table:
 *** 5.1.3-1 500
        500 http://ppa.launchpad.net/mrazavi/openvas/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
```

worked after that for me.

**Comment by dbellavista** [comment]
Thank you very much! A rebuild should fix it, right @mikesplain ?

**Comment by samos123** [comment]
would be great if the docker image could get pushed with this latest patch. I seem to have hit the same isssue and the workaround worked fine.

**Comment by mwild1** [comment]
It looks like the image was updated with 5.1.3 and this issue can be closed :+1:
