### ISSUE TITLE
How to config mail tool directly using External SMTP?

### ISSUE THREAD

**Issue by MyLike2018** [mikesplain/openvas-docker#213]

**Comment by MyLike2018** [comment]
When I use Postfix to send email , It always show the error.
(lost connection with smtp.163.com[220.181.12.18] while receiving the initial server greeting)

**Comment by meigea** [comment]
@MyLike2018 have you tried it sucess, chinese friend, you can connect me with email-actable@gmail.com; i can tell you more about openvas-deploy and some ways for using openwas
