### ISSUE TITLE
The request contained an unknown or invalid Host header OpenVAS error

### ISSUE THREAD

**Issue by kishoregurram** [mikesplain/openvas-docker#222]
Hi, I have followed the docker installation and configured the OpenVAS in it. Now when i try to access the console through browser, i am getting the error **'The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it.'**

I have also tried re-installing the OS but still the issue remains the same. Help is needed bit urgent. Please help me in this regard.

OS used: 
CentOS 7
Ubuntu 18.10

**Comment by adziubin** [comment]
try to add 
PUBLIC_HOSTNAME: <domain name>
in docker-compose openvas environment
