### ISSUE TITLE
Security issue Score 10.0 concering outdated Scan Engine / Environment (local)

### ISSUE THREAD

**Issue by AndrewBedscastle** [mikesplain/openvas-docker#224]
Reports say scan engine is outdated.
Can I fix this locally? Or does the container need an update
I tried an apt-get install openvas9-scanner inside an interactive bash but that gave me errors.
How can I check the installed version? How can I update it.

Installed GVM version:        9.0.2
Latest available GVM version: 9.0.3
Reference URL:                https://community.greenbone.net/t/gvm-9-stable-initial-release-2017-03-07/211

**Comment by cfi-gb** [comment]
https://github.com/Atomicorp/openvas/issues/7#issuecomment-479943352:
> Just a short note / some backgrounds on this. It was chosen to report a severity of 10.0 even if this is not actually vulnerability on the remote host for the following reason:
>
> There where two serious bugs fixed in the scheduler of openvas-scanner in [5.1.2](https://github.com/greenbone/openvas-scanner/releases/tag/v5.1.2) and [5.1.3](https://github.com/greenbone/openvas-scanner/releases/tag/v5.1.3) which could cause a lower coverage of vulnerabilities found on the remote host.
> 
> The severity might be decreased to a "0.0" / Log level entry in the future or once there is a better way to notify users of outdated components more prominently.

**Comment by Kars-de-Jong** [comment]
I don't have this issue. Your container probably needs an update. Just pull it again.

**Comment by AndrewBedscastle** [comment]
You were right. That worked.
Dunno, why I did not try that :)
This issue can be closed.
