### ISSUE TITLE
Dockerfile context

### ISSUE THREAD

**Issue by xaerowalk** [mikesplain/openvas-docker#230]
[Dockerfile](https://github.com/mikesplain/openvas-docker/blob/master/9/Dockerfile)
```
FROM mikesplain/openvas

FROM ubuntu:16.04
```
What's the point of use two 'FROM' ?

**Comment by mikesplain** [comment]
Openvas requires a few GB of data that gets synced during builds. By first copying that data, the sync goes much quicker and it speeds up our builds significantly.
