### ISSUE TITLE
Cannot access OpenVAS web server via port 443 on remote server

### ISSUE THREAD

**Issue by M1dor1ya** [mikesplain/openvas-docker#232]
I have met the same problem as this issue: https://github.com/mikesplain/openvas-docker/issues/191
I followed README to start a container with `docker run -d -p 443:443 -p 9390:9390 -e PUBLIC_HOSTNAME='my_ip' --name openvas mikesplain/openvas`,but it didn't work.
When i visit https://openvas_ip_address,i got an error msg:"The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it."

**Comment by liketop** [comment]
Same issue for me.
Seems like the webserver is not starting properly.
`curl 172.17.0.5:443
curl: (52) Empty reply from server`
