### ISSUE TITLE
Synology NAS - docker?

### ISSUE THREAD

**Issue by joosept** [mikesplain/openvas-docker#233]
Should this work on Synology Docker also or what am i missing?
I am using the lastest Synology DSM and Docker app.
I have bridge network with firewall rules enabled, also my second conteiner for Unifi works.
Both local and container ports are set the same.
Openvas conteiner starts, but i cannot connect to it via Web, it wont open and the Log says:
Failed to parse client XML: Error on line 1 char 1: Document must begin with an element (e.g. <book>) | stdout
-- | --

**Comment by hacker-h** [comment]
Please provide detailed outputs and describe the exact steps you made.
If Docker correctly runs on your system this like many other images should run as expected.
