### ISSUE TITLE
The latest version is 7.0.3?

### ISSUE THREAD

**Issue by davorceman** [mikesplain/openvas-docker#234]
Hello, I just installed image mikesplain/openvas:latest and mikesplain/openvas:9, but when I logged in, or check version with cli, I noticed that 7.0.3 is installed.

How to install version 9?

**Comment by baracoder** [comment]
Looks to me also that the latest version is 7.0.3 (both latest and 9 tags) 
It says so on the Help -> About page

> Greenbone Security Assistant
Version 7.0.3
