### ISSUE TITLE
Cannot run "openvas-mkcert -f -q " command

### ISSUE THREAD

**Issue by githubjqh** [mikesplain/openvas-docker#239]
I start the container with command
`docker run -d -p 443:443 -p 9390:9390 --name openvas mikesplain/openvas`
and get logs
`Step 1: Checking OpenVAS Scanner ...
        OK: OpenVAS Scanner is present in version 5.1.3.
        OK: OpenVAS Scanner CA Certificate is present as .
dirname: missing operand
Try 'dirname --help' for more information.
        ERROR: No server certificate file of OpenVAS Scanner found.
        FIX: Run 'openvas-mkcert -f -q'.
`
When I run "openvas-mkcert -f -q", get
`bash: openvas-mkcert: command not found`

**Comment by koenvervloesem** [comment]
In OpenVAS 9, the `openvas-mkcert` and `openvas-mkcert-client` commands have been replaced by `openvas-manage-certs`.
