### ISSUE TITLE
Getting “Result: Report outdated Scan Engine / Environment (local)” reports

### ISSUE THREAD

**Issue by 2nutz4u** [mikesplain/openvas-docker#251]
I get the following report Result: Report outdated / end-of-life Scan Engine / Environment (local) after a scan.  I have deleted and rebuilt the docker image but the problem persist.
Similar issue reported here
https://community.greenbone.net/t/openvas-9-0-1-update-to-9-0-3-centos/1859

Thank you.

**Comment by mrod23** [comment]
Getting the same issue, 
GVM needs to be updated 
Seeing this in the every report:
Installed GVM Libraries (gvm-libs) version:        9.0.3
Latest available GVM Libraries (gvm-libs) version: 10.0.1
Reference URL(s) for the latest available version: https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674 / https://community.greenbone.net/t/gvm-10-old-stable-initial-release-2019-04-05/208

Installed   GVM Libraries (gvm-libs) version:          9.0.3     Latest available GVM Libraries (gvm-libs) version: 10.0.1     Reference URL(s) for the latest available version:   https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674   /   https://community.greenbone.net/t/gvm-10-old-stable-initial-release-2019-04-05/208
--



Installed   GVM Libraries (gvm-libs) version:          9.0.3     Latest available GVM Libraries (gvm-libs) version: 10.0.1     Reference URL(s) for the latest available version:   https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674   /   https://community.greenbone.net/t/gvm-10-old-stable-initial-release-2019-04-05/208
--

**Comment by richardklein** [comment]
is there any update on this?

**Comment by mattdavenport** [comment]
It appears the latest version has been updated to 10, but the image is lagging behind in versions so the scanner is complaining.

**Comment by kampfflunder** [comment]
Maybe it is possible to update GVM from within the container?
If so: how?

**Comment by iamjoeker** [comment]
Updating requires downloading and recompiling the updated components. I'm working on an alternative docker image including the latest version of everything. I will either share here or PR it once I've got it working acceptably.

**Comment by mayantec** [comment]
Thanks in advance, we will wonder to try it out.

**Comment by mayantec** [comment]
> Updating requires downloading and recompiling the updated components. I'm working on an alternative docker image including the latest version of everything. I will either share here or PR it once I've got it working acceptably.

Did You succeed?

**Comment by xoroz** [comment]
let us know if there is a version 10 avail? 

thank you

**Comment by kukulkanos** [comment]
Done, for now:

docker run --name=openvas -d -ti -p 9443:9443 m4ch1n3s/openvas20
Wait for 10 minutes or 15 to get up to date, and then change the password
docker exec -ti openvas gvmd --user=admin --new-password=new_password

and go trow https://ip:9443

**Comment by koonoh** [comment]
> Done, for now:
> 
> docker run --name=openvas -d -ti -p 9443:9443 m4ch1n3s/openvas20
> Wait for 10 minutes or 15 to get up to date, and then change the password
> docker exec -ti openvas gvmd --user=admin --new-password=new_password
> 
> and go trow https://ip:9443

Thanks, works as expected.

**Comment by tuwid** [comment]
@kukulkanos can you give us the code for how you build this? 
I wouldn't run a security scanner with my keys with an untrusted image from the internet

**Comment by kukulkanos** [comment]
@tuwid Here is a bunch of files I've rescued from my build machine, you have to provide the downloadables, because if I provide so, will loose the purpose of building a trustable image.
Put all the files in the source folder that is not existent, also the initial feeds if you want to save some time, because is not the same update than download for the very first time (in the feeds folder, non existent). Also could happen that will not work, because was created in december 2021. [https://github.com/kukulkanos/openvascontainer](https://github.com/kukulkanos/openvascontainer )

**Comment by tuwid** [comment]
Thank you sir!
