### ISSUE TITLE
Version question

### ISSUE THREAD

**Issue by frakman1** [mikesplain/openvas-docker#252]
I ran docker pull on images `mikesplain/openvas` and `mikesplain/openvas:9`  but they both result in containers that yield old versions (7 and not 9). How come?

```bash
# /usr/sbin/gsad --version
Greenbone Security Assistant 7.0.3
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

# /usr/sbin/openvasmd --version
OpenVAS Manager 7.0.3
Manager DB revision 184
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

# /usr/sbin/openvassd --version
OpenVAS Scanner 5.1.3
Most new code since 2005: (C) 2016 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

The WebUI (gad) also shows version 7.0.3
![image](https://user-images.githubusercontent.com/5826484/86516438-88033880-bdee-11ea-9e60-ff88c01b523d.png)

![image](https://user-images.githubusercontent.com/5826484/86516449-981b1800-bdee-11ea-93bb-37f9f1157347.png)

**Comment by xoroz** [comment]
Hi there,
I have the same issue.
There will be support for version 10 ?

**Comment by plangeard** [comment]
Hi there,
It look there is no more update (last update 2 years ago).
Did you find another images ?

**Comment by frakman1** [comment]
I've been using version 11 from this docker location: `securecompliance/gvm:11.0.1-r3`

There are more recent tags/releases here:

https://registry.hub.docker.com/r/securecompliance/gvm/tags
