### ISSUE TITLE
There is a problem with HTTP access

### ISSUE THREAD

**Issue by SecReXus** [mikesplain/openvas-docker#253]
When visiting the page, you will be prompted as follows：
The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it.

**Comment by wisoez** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10806362/91520778-51dec280-e920-11ea-8ae3-06935349c533.png)
Same issue!

**Comment by wisoez** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/10806362/91521113-23151c00-e921-11ea-8584-7978568efd78.png)
Same issue!
This is my docker run:
`docker run -d -p 443:443 -e ALLOW_HEADER_HOST=openvas.xxx.xx -e PUBLIC_HOSTNAME=openvas.xxx.xx -v $(pwd)/data:/var/lib/openvas/mgr/ -e OV_PASSWORD=xxx -e OV_SMTP_HOSTNAME=smtp.gmail.com -e OV_SMTP_PORT=587 -e OV_SMTP_USERNAME=xxx@gmail.com -e OV_SMTP_KEY=xxx --name openvas mikesplain/openvas`

**Comment by wisoez** [comment]
1. Access to container's bash: docker exec -it openvas bash
2. Open file: /etc/default/openvas-gsa (note: apt update -y && apt install vi vim -y)
`vim /etc/default/openvas-gsa`
3. Add this line:
`ALLOW_HEADER_HOST=PUT YOUR HOST NAME or IPADDRESS HERE`
4. Restart /etc/init.d/openvas-gsa restart
5. Check on browser.

**Comment by costabh** [comment]
@wisoez if i wanted to open to everyone, i just put 0.0.0.0 or have another wildcard for this option?
