### ISSUE TITLE
I think this one can help you😉

### ISSUE THREAD

**Issue by coumbisskante** [mikesplain/openvas-docker#257]
I had the same problem and this following page:https://sys-guard.com/post-18431/ helps me to resolve the Problem. It's in Japanese but you can translate into English. Like explained in the link, the prblem is from the files usr/sbin/greenbone-nvt-sync | greenbone-certdata-sync | greenbone-scapdata-sync. The link: feed.openvas.org is not available since 30 September 2020. The link will help you to change  it into the new link.😊

**Comment by drwetter** [comment]
Thanks! Quickfix:

```
for f in /usr/sbin/greenbone-certdata-sync /usr/sbin/greenbone-nvt-sync /usr/sbin/greenbone-scapdata-sync; do
     sed -i 's/feed.openvas.org/feed.community.greenbone.net/' $f
done
```
