### ISSUE TITLE
how to change rsync feed

### ISSUE THREAD

**Issue by stef97** [mikesplain/openvas-docker#258]
RSYNC does not work because it is configured to use this feed feed.openvas.org

It does work though if we are using feed.community.greenbone.net

I tested by changing in the container using sed 

Is there a variable similar with PUBLIC_NAME that can be used when building container ?
..or any other smarted way to deal with this ?
Thanks

**Comment by drwetter** [comment]
Hmm.. just stumbled over this too. feed.community.greenbone.net does use a CN which is wrong:

```
 Common Name (CN)             files.greenbone.net 
 subjectAltName (SAN)         files.greenbone.net 
```

Anybody knows what is going on here?

**Comment by drwetter** [comment]
see also #257

**Comment by nick-fox** [comment]
Add rsync feeds to your env.

```
declare -x COMMUNITY_CERT_RSYNC_FEED="rsync://feed.community.greenbone.net:/cert-data"
declare -x COMMUNITY_NVT_RSYNC_FEED="rsync://feed.community.greenbone.net:/nvt-feed"
declare -x COMMUNITY_SCAP_RSYNC_FEED="rsync://feed.community.greenbone.net:/scap-data"
```

I've tested this running the docker image https://hub.docker.com/r/mikesplain/openvas
