### ISSUE TITLE
funkyfuture/deck-chores doesn't have `latest` tag

### ISSUE THREAD

**Issue by larsnaesbye** [mikesplain/openvas-docker#260]
funkyfuture/deck-chores has no `latest` tag on Docker Hub. Maybe the cron container should specify `funkyfuture/deck-chores:1` instead?

Currently the docker-compose fails because of this.

**Comment by larsnaesbye** [comment]
@mikesplain is something you'd like to incorporate? :-)

**Comment by larsnaesbye** [comment]
@mikesplain if I make a PR would it get merged?

**Comment by falconws** [comment]
@mikesplain @larsnaesbye This is fact.

```
$ docker-compose up -d
Pulling cron (funkyfuture/deck-chores:)...
ERROR: manifest for funkyfuture/deck-chores:latest not found: manifest unknown: manifest unknown
```

https://github.com/mikesplain/openvas-docker/issues/260#issue-740104618
is right?
Why closed this issue?

**Comment by larsnaesbye** [comment]
@falconws I closed my own issue because I gave up and found https://github.com/immauss/openvas instead.
