### ISSUE TITLE
Update NVT feed location

### ISSUE THREAD

**Issue by hugeps** [mikesplain/openvas-docker#263]
[https://community.greenbone.net/t/shutting-down-gcf-http-download/5339](https://community.greenbone.net/t/shutting-down-gcf-http-download/5339)

Community feed is now located here

feed.community.greenbone.net:

IP address: 2a0e:6b40:20:106:20c:29ff:fe67:cbb5
Legacy IP address: 45.135.106.142

**Comment by ramonchiara** [comment]
One way around this problem is to run `export COMMUNITY_NVT_RSYNC_FEED=rsync://feed.community.greenbone.net:/nvt-feed` before running `greenbone-nvt-sync´

So, @mikesplain might update this section in `README.md`:

```
docker exec -it openvas bash
## inside container
```
**`export COMMUNITY_NVT_RSYNC_FEED=rsync://feed.community.greenbone.net:/nvt-feed`**
```
greenbone-nvt-sync
openvasmd --rebuild --progress
greenbone-certdata-sync
greenbone-scapdata-sync
openvasmd --update --verbose --progress

/etc/init.d/openvas-manager restart
/etc/init.d/openvas-scanner restart
```

**Comment by huornlmj** [comment]
Is @mikesplain still maintaining this?

**Comment by ghostersk** [comment]
I just run the container with this:
        docker stop openvas && docker rm openvas

        docker pull mikesplain/openvas
        docker run -d -p 3344:443 -p 9390:9390 \
                -e PUBLIC_HOSTNAME=openvas.freebede.com \
		-e FEED="feed.community.greenbone.net" \
		-e COMMUNITY_NVT_RSYNC_FEED="rsync://$FEED:/nvt-feed" \
		-e COMMUNITY_CERT_RSYNC_FEED="rsync://$FEED:/cert-data" \
		-e COMMUNITY_SCAP_RSYNC_FEED="rsync://$FEED:/scap-data" \
                --network nginxproxymgr_default \
                --name openvas \
                -h openvas \
                -v /opt/openvas/mgr:/var/lib/openvas/mgr/ \
                mikesplain/openvas

**Comment by makarov20211221** [comment]
Thank you ramonchiara, perfectly solved this problem

**Comment by dreddsa5dies** [comment]
You can also edit the configuration file in the container itself according to the [method](https://debugah.com/solved-fsync-failed-to-connect-to-feed-openvas-org-89-146-224-58-25262/)
