### ISSUE TITLE
some "mistakes" with this docker image 

### ISSUE THREAD

**Issue by oldunclez** [mikesplain/openvas-docker#264]
It seems that there are some mistakes with this docker image so far  .

The following mistakes  are  in script file  "/openvas-check-setup"  inside docker image

### Mistake 1:
The code `if [ ! -e $CAFILE ]`    does not work , it should be  `if [ ! -e "$CAFILE" ]`  .

### Mistake 2:
> CAFILE=`openvassd -s 2>>$LOG | grep ca_file | sed -e "s/^ca_file = //"`

`openvassd -s` will not show out cafile  , so CAFILE is Null ,  but they are there (/var/lib/openvas/CA/) in fact .
so it will throw out error like this : https://github.com/mikesplain/openvas-docker/issues/262

### Mistake 3:
The verison of  OpenVAS Manager inside docker image is 7.0.3,
but "/openvas-check-setup" script will need "6.1"

> ERROR: OpenVAS Manager too old or too new: 7.0.3
> FIX: Please install OpenVAS Manager 6.1.

**Comment by CoffeeNData** [comment]
This.
I get the error referenced in #262 . Im still trying to figure out a workaround.
