### ISSUE TITLE
Cannot update NVTs

### ISSUE THREAD

**Issue by stu93303148** [mikesplain/openvas-docker#266]
<img width="1002" alt="截圖 2021-07-07 下午5 34 20" src="https://user-images.githubusercontent.com/1113604/124736429-94fac080-df49-11eb-9152-3610e3e68d68.png">

**Comment by ramonchiara** [comment]
@stu93303148, have you read https://github.com/mikesplain/openvas-docker/issues/263?
Please, verify if it helps.

**Comment by stu93303148** [comment]
Thanks your help. Updated success.
