### ISSUE TITLE
ERROR: manifest for funkyfuture/deck-chores:latest not found

### ISSUE THREAD

**Issue by songwutk** [mikesplain/openvas-docker#273]
After run docker-compose up 

ERROR: for cron  manifest for funkyfuture/deck-chores:latest not found: manifest unknown: manifest unknown
ERROR: manifest for funkyfuture/deck-chores:latest not found: manifest unknown: manifest unknown

**Comment by cfi-gb** [comment]
Keep in mind that this docker container seems to be really outdated, haven't received updates since many years and shouldn't be used in production these days, see e.g. #271
