### ISSUE TITLE
Creating a credential in the web interface breaks all further actions

### ISSUE THREAD

**Issue by siliconcow** [mikesplain/openvas-docker#44]
I can load the web interface but any change to create something like a target doesn't work, it just hangs forever.

Logs have:
gsad main:WARNING:2015-08-27 19h22.38 UTC:613: MHD: Failed to receive data: A TLS packet with unexpected length was received.
(repeating)

[Sat Jul 11 05:49:32 2015][38] openvassd 4.0.7 started
[Sat Jul 11 05:54:47 2015][347] Communication closed by client
[Sat Jul 11 05:54:47 2015][347] Client not present
[Thu Aug 27 19:02:43 2015][11] openvassd 4.0.7 started
[Thu Aug 27 19:04:41 2015][599] Communication closed by client
[Thu Aug 27 19:04:41 2015][599] Client not present
[Thu Aug 27 19:05:27 2015][615] openvassd 4.0.7 started
[Thu Aug 27 19:05:28 2015][627] Communication closed by client
[Thu Aug 27 19:05:28 2015][627] Client not present
(repeating)

root@b22110a62c70:/usr/local/var/log/openvas# cat openvasmd.log
md   main:WARNING:2015-07-11 05h54.44 utc:346: sql_x_internal: sqlite3_prepare failed: no such table: main.meta
lib auth:   INFO:2015-07-11 05h54.47 utc:351: Authentication configuration not found.
lib auth:   INFO:2015-07-11 05h54.47 utc:352: Authentication configuration not found.
lib auth:   INFO:2015-08-27 19h04.41 utc:603: Authentication configuration not found.
md   main:CRITICAL:2015-08-27 19h04.41 utc:603: main: database is wrong version
lib auth:   INFO:2015-08-27 19h04.41 utc:604: Authentication configuration not found.
lib auth:   INFO:2015-08-27 19h04.42 utc:611: Authentication configuration not found.
md    otp:MESSAGE:2015-08-27 19h05.19 UTC:622: Scanner loading: 37350 / 39585 nvts.
md    otp:MESSAGE:2015-08-27 19h05.20 UTC:623: Scanner loading: 37750 / 39585 nvts.
base gpgme:MESSAGE:2015-08-27 19h08.20 UTC:633: Setting GnuPG homedir to '/usr/local/var/lib/openvas/gnupg'
base gpgme:MESSAGE:2015-08-27 19h08.21 UTC:633: Using OpenPGP engine version '1.4.16'
md  crypt:   INFO:2015-08-27 19h08.21 UTC:633: starting key generation ...
lib   rer:WARNING:2015-08-27 19h14.53 UTC:679: Target source configuration could not be loaded.
lib   rer:WARNING:2015-08-27 19h23.00 UTC:716: Target source configuration could not be loaded.
md   main:   INFO:2015-08-27 19h26.44 utc:790:    OpenVAS Manager

**Comment by mikesplain** [comment]
Hmm interesting.  Looks like the NVTs didn't load properly.  Can you confirm in the UI, click "SecInfo Management", then "NVTs".  I imagine it has 0 listed NVTs?

**Comment by mikesplain** [comment]
Also what version of docker are you running?

**Comment by siliconcow** [comment]
I'm running docker version 1.6.2...

I realize it was actually the first thing I did - creating a credential - which broke it.   I recreated the container and was able to add a target as expected.    It looks like openvas forked GPG which is having issues and seems to be hanging things.

**Comment by mikesplain** [comment]
I believe this was fixed in newer versions.  Not seeing an issue anymore.  Reopen if you experience it again.
