### ISSUE TITLE
Consider switching to supervised

### ISSUE THREAD

**Issue by mikesplain** [mikesplain/openvas-docker#58]
Should considering using supervised to run services rather than silly bash files...

**Comment by aphillipo** [comment]
Here is a supervisord config I found somewhere...

[program:openvassd]
autostart=true
command=/usr/local/sbin/openvassd -f
stdout_logfile = /var/log/dave/%(program_name)s.log
stderr_logfile = /var/log/dave/%(program_name)s.log
autorestart=true
startsecs=0

[program:openvasmd]
autostart=true
command=/usr/local/sbin/openvasmd -f
stdout_logfile = /var/log/dave/%(program_name)s.log
stderr_logfile = /var/log/dave/%(program_name)s.log
autorestart=true
startsecs=0

[program:gsad]
autostart=true
command=/usr/local/sbin/gsad -f
stdout_logfile = /var/log/dave/%(program_name)s.log
stderr_logfile = /var/log/dave/%(program_name)s.log
autorestart=true
startsecs=0

[program:redis-server]
autostart=true
command=/usr/bin/redis-server /etc/redis/redis.conf
stdout_logfile = /var/log/dave/%(program_name)s.log
stderr_logfile = /var/log/dave/%(program_name)s.log
autorestart=true
startsecs=0

**Comment by mikesplain** [comment]
@aphillipo Thanks!

**Comment by berney** [comment]
I hear S6 is all the rage for containers, but then so is Alpine.

**Comment by mikesplain** [comment]
For now we'll use built in upstart.

**Comment by aphillipo** [comment]
Even better 👍🏻

**Comment by mikesplain** [comment]
And by upstart I meant systemd, as that's now the default in 16.04.
