### ISSUE TITLE
Error on Login Screen

### ISSUE THREAD

**Issue by darioajr** [mikesplain/openvas-docker#69]
An error occurs when trying to log into the system

Error:
Login failed. OMP service is down.

How to fix it:
docker exec -it CONTAINER_ID bash
openvas-nvt-sync
openvasmd --rebuild
openvasmd

**Comment by mikesplain** [comment]
Does this happen all the time or every time you start it up?

**Comment by mikesplain** [comment]
Closing since no response.  Please repost if still an issue.
