### ISSUE TITLE
Error when login to Openvas web ui

### ISSUE THREAD

**Issue by ayen-tibco** [mikesplain/openvas-docker#74]
This error happens when after submitting a scan task or just login to the webui of Openvas.

-Adam

Starting infinite loop...
Press [CTRL+C] to stop..
Ohhhh jeeee: ... this is a bug (sexp.c:1340:vsexp_sscan)

**Comment by mikesplain** [comment]
@ayen-tibco I can't reproduce this. What is your command you're using to the container, and can you send the full log?

**Comment by ayen-tibco** [comment]
docker run -d -p 443:443 -p 9390:9390 -p 9391:9391 --name openvas mikesplain/openvas

Could be I'm running it in virtualbox (Docker Toolbox for Windows)?

-Adam

**Comment by mikesplain** [comment]
This could be related to windows but I'm still surprised.  Can you provide a full log of the output?
