### ISSUE TITLE
Persistent volumes

### ISSUE THREAD

**Issue by azimut** [mikesplain/openvas-docker#76]
Test and document volumes for persistence of the reports.

**Comment by andreaslang** [comment]
I gave this one a shot and for me it seemed to work keeping user settings by just creating a volume for /var/lib/openvas/mgr:

```bash
mkdir ~/mgr
docker run --name openvas -d -p 4000:4000 -v /home/your-user/mgr/:/var/lib/openvas/mgr/ mikesplain/openvas:9
```

You just need to create the default user yourself

```bash
docker exec -ti openvas openvasmd --create-user=admin
docker exec -ti openvas openvasmd --user=admin --new-password=super_secret_password
```

**Comment by mikesplain** [comment]
Thanks for our help! I added support for this and documented it in the repo. Let me know if you have any issues!
