### ISSUE TITLE
No user created at deployment?

### ISSUE THREAD

**Issue by falkowich** [mikesplain/openvas-docker#81]
Hi,

I deployed the image a few time to test it out if I'm doing things wrong.

But when the rebuild of rules is done I try to login to gsad webui, and no cigarr.

If I do a check of the installation with /openvas/openvas-check-setup 
```
        ERROR: No users found. You need to create at least one user to log in.
        It is recommended to have at least one user with role Admin.
        FIX: create a user by running 'openvasmd --create-user=<name> --role=Admin && openvasmd --user=<name> --new-password=<password>'
```

This fixes the problem.. 

Is this me doing stuff the wrong way, or a bug?

--
Regards Falk

**Comment by mikesplain** [comment]
Ahh yes, looks like that was changed with the new release.  Looking into it now.
