### ISSUE TITLE
verinice export 0Byte

### ISSUE THREAD

**Issue by mrmueller** [mikesplain/openvas-docker#87]
Hi, thanks for providing this image, it is very convenient  :)

Sadly, the exports for verinice (Verinice ITG & Verninice ISM) don't seem to work, they have zero content.

I suspect it is related to this bug report: http://wald.intevation.de/tracker/?func=detail&atid=220&aid=6754&group_id=29

could you add xmlstarlet and xsltproc to the dockerfile?

**Comment by mikesplain** [comment]
Hi Martin!

You're quite welcome! FYI that link doesn't work for me. 

If you'd like to open a PR I would gladly accept it, otherwise I might not get to looking at this till next week.

**Comment by mrmueller** [comment]
they seem to use an untrusted certificate.

These are the essentials:
_**Genaue Beschreibung**
When you export a report as verinice-file, the file has 0Bits and is empty._ 
_**Datum: 26.02.2016 08:23
Sender: eero volotinen**
works for me, if xmlstarlet and xsltproc is installed in system._

I'll try to do a PR :)
