### ISSUE TITLE
Creating credentials

### ISSUE THREAD

**Issue by andyp888** [mikesplain/openvas-docker#91]
On a fresh install of this image on docker, if I try to create a new credential via the GUI the browser just hangs and will never complete this task.  I have tried various solutions found on the internet to no avail.

**Comment by sc-pulsion** [comment]
Are you running Ubuntu on Hyper-V by any chance?

Try run like this:

`docker run -v /dev/urandom:/dev/random -d -p 443:443 -p 9390:9390 -p 9391:9391 --name openvas mikesplain/openvas`

**Comment by mikesplain** [comment]
@andyp888 are there any errors in the logs? @sc-pulson is right, I've seen odd behavior on different platforms with this image. I haven't been able to solve them. Most Linux based systems don't need the urandom mount however I've had issues with running actual scans on docker for mac. 

Any more details to help us diagnose? E.g. Where you're running it, what version of docker?

**Comment by mikesplain** [comment]
@sc-pulsion sorry for the typo!

**Comment by andyp888** [comment]
@sc-pulsion I am running Ubuntu 14.04 on a VM, not on Hyper-V though

@mikesplain I am running docker client 1.6.2.  One of the "solutions" I found online was to run the openvasmd --create-credentials-encryption-key command.  However I get the following error in the openvasmd.log file:

md  crypt:WARNING:2016-10-12 13h21.26 utc:271: error creating OpenPGP key 'OpenVAS Credential Encryption': Inappropriate ioctl for device <GPGME>

Nothing shows up in the log about creating the credentials though strangely.

**Comment by andyp888** [comment]
I guess I can close this issue, for some reason leaving the credentials to generate eventually seems to work, and from then creating more credentials is fast.  It did take multiple hours for the first set of credentials to be created though.
