### ISSUE TITLE
FATA[0024] Tag latest not found in repository mikesplain/openvas 

### ISSUE THREAD

**Issue by tuhaolam** [mikesplain/openvas-docker#92]
I retry docker pull for many many times, but always the exception it raise above. Is it a networking problem? But I can access docker hub normally.

**Comment by mikesplain** [comment]
I'll issue a rebuild to see if that helps.

**Comment by mikesplain** [comment]
Works fine for me, have you tried pulling another container (e.g. redis) to ensure you're not having network connectivity issues yourself? Closing for now unless we discover a real issue.
